---
abstract: 'Use YAML::Tiny like JSON'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-Tiny-LikeJSON
recommends: {}
requires: {}
version: 0.0010
